baseURL = '/'
languageCode = 'en-us'
title = 'Slice325 Learn'
theme = "hugo-theme-learn"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "slice325"
  landingPageURL = '/slice325'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
[minify]
  disableHTML = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
